from __future__ import annotations

from typing import Protocol


class HardwareController(Protocol):
    def set_light_schedule(self, start_hour: int, end_hour: int) -> None: ...

    def set_light_manual(self, state: bool) -> None: ...

    def water_plant(self, plant_name: str, duration_seconds: int = 5) -> None: ...

    def fertilize(self, plant_name: str, fert_type, duration_seconds: int = 3) -> None: ...

    def get_temperature(self) -> float: ...

    def get_humidity(self) -> int: ...

    def update_garden(self, garden_plants: list) -> None: ...

    def start_auto_mode(self) -> None: ...

    def stop_auto_mode(self) -> None: ...

    def cleanup(self) -> None: ...
